### ISSUE TITLE
Are there any plans to update API 9 (6.5)?

### ISSUE THREAD

**Issue by lemonmousse** [emptyset0/Radar_akira0245#1]
thx!

**Comment by emptyset0** [comment]
Here is a test build.
However, I don't know whether it works or not, since I have no intl game account to debug.
[radar_api9_test.zip](https://github.com/emptyset0/Radar_akira0245/files/14140039/radar_api9_test.zip)

**Comment by lilycry3084** [comment]
radar plugin is the best FFXIV addons that i used. i love deepdungens i love radar plugin!~ ^^

________________________________
发件人: emptyset0 ***@***.***>
发送时间: 2024年2月2日 10:08
收件人: emptyset0/Radar_akira0245 ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [emptyset0/Radar_akira0245] Are there any plans to update API 9 (6.5)? (Issue #1)


Here is a test build.
However, I don't know whether it works or not, since I have no intl game client to test.
radar_api9_test.zip<https://github.com/emptyset0/Radar_akira0245/files/14138550/radar_api9_test.zip>

―

**Comment by emptyset0** [comment]
Plugin updated.
